USE [master]
GO

/****** Object:  Database [Portfolio]    Script Date: 1/30/2022 2:03:52 PM ******/
CREATE DATABASE [Portfolio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Portfolio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Portfolio.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Portfolio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Portfolio_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Portfolio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Portfolio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Portfolio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Portfolio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Portfolio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Portfolio] SET ARITHABORT OFF 
GO

ALTER DATABASE [Portfolio] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Portfolio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Portfolio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Portfolio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Portfolio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Portfolio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Portfolio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Portfolio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Portfolio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Portfolio] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Portfolio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Portfolio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Portfolio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Portfolio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Portfolio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Portfolio] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Portfolio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Portfolio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Portfolio] SET  MULTI_USER 
GO

ALTER DATABASE [Portfolio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Portfolio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Portfolio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Portfolio] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Portfolio] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Portfolio] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Portfolio] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Portfolio] SET  READ_WRITE 
GO

